# Example configuration file

#Database configuration
database:
  host: "111.111.111.111"
  port: 1000
  user: "root"
  password: ""
  database: "dev"
redis:
    addr: "111.111.111.111:2000"
    password: ""

# JWT configuration
jwt:
    secret: ""
    expiration: 3600  # seconds

# Service configuration
service:
    secret:
        login_token_salt: ""

storage:
    local:
        root_path: "/var/app/storage"


# Logging configuration
# logging:
#   level: "info"  # debug, info, warn, error
#   format: "json"  # json, text
